project:
  type: website
  output-dir: docs
  resources: 
   - 01_intro.pdf

website:
  title: "Stats4schools"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



