---
title: "Analisi di dati ambientali tramite risorse open source per la Data Science"
author: "Riccardo Borgoni, Roberto Ascari e Paolo Maranzano"
institute: "Università di Milano-Bicocca"
date: today
---

# Programma del corso


Il corso fornisce alcune informazioni di base su un applicativo software di tipo open source per l’analisi statistica delle serie temporali e spaziali di dati ambientali. Saranno descritti i principali operatori di sintesi dei dati e strumenti per la loro rappresentazione grafica. Verrà introdotto il concetto di geolocalizzazione dell’informazione e i principali formati di dati spaziali (raster e vettoriali). Si introdurranno infine alcune tecniche per l’interpolazione di serie temporali e spaziali e alcune esemplificazioni relative alla realizzazione di mappe tematiche.

1.    Introduzione al software di tipo open source per l’analisi dei dati.

2.    Descrizione quantitativa dei dati ambientali.

3.    L’analisi delle serie temporali di indicatori ambientali.

4.    La georeferenziazione dei dati.

5.    L’analisi dei dati spaziali e territoriali. 

6.    La realizzazione di mappe tematiche.



# Calendario degli incontri

Gli incontri si svolgeranno secondo il seguente calendario:

-   Giovedì 6 Febbraio 2025, 09.30-13.30, lab 908 ([edificio U9 - KOINÈ](https://maps.app.goo.gl/JyDtaHD5Jjffjsoa7))

-   Giovedì 13 Febbraio 2025, 09.30-13.30, lab 719 ([edificio U7 - CIVITAS](https://maps.app.goo.gl/dnad4RbTTkhq3fX36))


-   Martedì 18 Febbraio 2025, 09.00-13.00, liceo Lussana di Bergamo

-   Mercoledì 26 Febbraio 2025, 10.00-13.00, liceo Lussana di Bergamo


# Link a R e RStudio

Ai seguenti link è possibile scaricare le ultime versioni di [R](https://cran.r-project.org/bin/windows/base/) e di [RStudio](https://posit.co/download/rstudio-desktop/).

# Link Condivisione schermo:

A [questo](https://meet.google.com/nfd-hrnu-sjb) link è possibile accedere ad una chiamata Google Meet in cui verrà condiviso lo schermo del docente per poter seguire la lezione.

# Materiale

## Slide
<!-- **Data** data for tutorials [excel](dat1.xlsx); [csv](dat1.csv); -->


1.  [Introduzione al progetto PNRR](Liceo Lussana_Bergamo_Slide informativa Percorso PNRR.pptx)

2. [Introduzione al corso](Slide/BSTAT5 - Intro.pdf)

3.  [Introduzione alla Statistica Descrittiva con R - Slide](Slide/BSTAT5 - IntroR.pdf)



## Script

1. [Introduzione alla Statistica Descrittiva con R - Script](IntroR/BSTAT5 - IntroR - Script.R)

2. [Interpolazione - Script](IntroR/interpolazione4s.R)


## Dati

1.  [Agrimonia - Metadati](Dati Agrimonia/LussanaPNRR - Metadata Agrimonia.xlsx)

2.  [Agrimonia - Dati](IntroR/Agrimonia.RData)

3.  [Agrimonia - Dati centraline](IntroR/Centraline.csv)

4. [Interpolazione - Dati](IntroR/Giornata2_Dati.zip)
